name: CI

on:
  pull_request:
    types: [ opened, synchronize, reopened ] 

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.15.0
    - run: npm install
    - run: |
        npm run lint
        npm run format:check